# Generated by Django 5.2.8 on 2025-12-01 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPresupuestaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cuenta', models.CharField(max_length=50, unique=True, verbose_name='Código Presupuestario')),
                ('nombre_cuenta', models.CharField(max_length=200, verbose_name='Nombre de la Cuenta')),
                ('presupuesto_inicial', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Presupuesto Inicial')),
                ('modificaciones', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Modificaciones Actuales')),
                ('presupuesto_vigente', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Presupuesto Final Vigente')),
            ],
        ),
        migrations.CreateModel(
            name='ComiteTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('miembros', models.ManyToManyField(related_name='comites_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('ADMINISTRADOR', 'Administrador Municipal'), ('DAF', 'Director de Finanzas'), ('DIDECO', 'Director DIDECO'), ('CONTROL', 'Director de Control'), ('ALCALDE', 'Alcalde'), ('SECPLAN', 'SECPLAN - Planificación'), ('DOM', 'DOM - Obras')], default='DIDECO', max_length=50)),
                ('es_jefe', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('comites_revisores', models.ManyToManyField(blank=True, to='gestion_municipal.comitetecnico')),
                ('director_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_dirigidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActividadProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=20, unique=True, verbose_name='ID Actividad')),
                ('nombre_actividad', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Completado', 'Completado'), ('Atrasado', 'Atrasado')], default='Pendiente', max_length=20)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_hijas', to='gestion_municipal.proyecto', verbose_name='Proyecto Padre')),
            ],
        ),
    ]
